version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: softka-rabbit
    hostname: my-softka-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
  sender:
    build: ./sender
    container_name: sender
    ports:
      - "8081:8081"
    volumes:
      - ./sender:/app
    depends_on:
      - rabbitmq
  receiver:
    build: ./receiver
    container_name: receiver
    ports:
      - "8082:8082"
    volumes:
      - ./receiver:/app
    depends_on:
      - sender
      - rabbitmq